export const UPDATE_SCREEN_HEIGHT = "UPDATE_SCREEN_HEIGHT";

export const UPDATE_DARKMODE = "UPDATE_DARKMODE";

export const UPDATE_DARKMODETOGGLE = "UPDATE_DARKMODETOGGLE";

export const UPDATE_REMEMBERMETOGGLE = "UPDATE_REMEMBERMETOGGLE";

export const UPDATE_GLOBAL_COLOR = "UPDATE_GLOBAL_COLOR";

export const ACTIVATE_GLOBAL_LOADER = "ACTIVATE_GLOBAL_LOADER";

export const HIDE_GLOBAL_LOADER = "HIDE_GLOBAL_LOADER";

export const CHANGE_OPTIONS_TOP = "CHANGE_OPTIONS_TOP";

export const CHANGE_NAV = "CHANGE_NAV";

export const CHANGE_NAV_FILTER = "CHANGE_NAV_FILTER";

export const CHANGE_NAV_CROP = "CHANGE_NAV_CROP";
